name: dart_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1  # Ensure this version or the latest stable one is used
  path_provider: ^2.0.14
  image_picker: ^1.0.7
  image_cropper: ^9.0.0
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.0.1
  speech_to_text: ^7.0.0
  image: ^4.1.3  # Latest version of Dart's image package
  google_ml_kit: ^0.19.0
  intl: ^0.20.2
  photo_view: ^0.14.0


# dependencies:
#   flutter:
#     sdk: flutter
#   camera: ^0.10.0
#   archive: ^3.3.0  # For extracting ZIP files
#   path_provider: ^2.0.14  # Add this dependency
#   image_cropper: ^5.0.0  # Ensure you use the latest version
#   image_picker: ^1.0.7  # To pick images
#   google_mlkit_text_recognition: ^0.14.0  # ML Kit for OCR
#   file_picker: ^8.0.0  # For picking files on Windows
#   permission_handler: ^11.0.1  # For requesting permissions
#   cupertino_icons: ^1.0.8
#   speech_to_text: ^7.0.0  # For converting speech to text
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
