name: dart_app

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  path_provider: ^2.0.14
  image_picker: ^1.0.7
  image_cropper: ^9.0.0
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.0.1
  speech_to_text: ^7.0.0
  image: ^4.1.3
  google_ml_kit: ^0.19.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  vm_service: 14.3.1  # ✅ Match Flutter Test's requirement
  camera_android_camerax: ^0.6.13
  async: ^2.12.0
  material_color_utilities: ^0.11.1  # ✅ Match Flutter Test's requirement
  font_awesome_flutter: ^10.6.0  # ✅ Added for extra icons
  flutter_sound: ^9.2.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.2  # ✅ Downgraded to match `flutter_test`
  leak_tracker: ^10.0.8  # ✅ Already fixed previously

flutter:
  uses-material-design: true
